# Specify the line length that the printer will wrap on.
printWidth: 80

# Specify the number of spaces per indentation-level.
tabWidth: 4

# Indent lines with spaces instead of tabs.
useTabs: false

# Print semicolons at the ends of statements.
semi: true

# Use double quotes instead of single quotes.
singleQuote: false

# Change when properties in objects are quoted.
quoteProps: "as-needed" # options: ["as-needed", "consistent", "preserve"]

# Print trailing commas wherever possible when multi-line.
trailingComma: "all" # options: ["none", "es5", "all"]

# Print spaces between brackets in object literals.
bracketSpacing: true

# Put the `>` of a multi-line block quote on a new line.
bracketSameLine: false

# Include parentheses around a sole arrow function parameter.
arrowParens: "always" # options: ["avoid", "always"]

# Prettier can restrict itself to only format files that contain a special comment,
# called a pragma, at the top of the file.
requirePragma: false

# Prettier can insert a special @format marker at the top of files specifying that the
# file has been formatted with Prettier.
insertPragma: false

# Enforce single attribute per line in HTML, Vue and JSX.
singleAttributePerLine: false

# Plugins
plugins: ["prettier-plugin-tailwindcss"]

# Override configuration for specific languages and files.
overrides:
  - files:
      - "*.sql"
      - "*.json"
      - "*.yml"
      - "*.yaml"
    options:
      tabWidth: 2
  - files:
      - "*.md"
      - "*.html"
    options:
      printWidth: 120
