version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}
    platform: linux/amd64
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - .:/app