version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    platform: linux/amd64
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
