name: Deploy to Docker Hub

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/sparplanrechner:latest" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/sparplanrechner:latest"
