name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install TailwindCSS
        run: bun add tailwindcss

      - name: Build the dist/ directory
        run: |
          bun tailwindcss -i ./web/src/style.css -o ./web/dist/style.css
          bun build web/src/main.ts --outdir web/dist

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --platform=linux/amd64 -t "${{ secrets.DOCKER_USERNAME }}/sparplanrechner:latest" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/sparplanrechner:latest"
