name: Pre-Commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go for golangci-lint
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"

      - name: Set up Python to install Pre-Commit
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Pre-Commit
        run: pip install pre-commit

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Prettier and ESLint
        run: |
          bun add prettier prettier-plugin-tailwindcss
          bun add eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - name: Run Pre-Commit
        run: pre-commit run --all-files
