name: Pre-Commit Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python to install Pre-Commit
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Pre-Commit
        run: pip install pre-commit

      - name: Set up Node.js to install Prettier
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Prettier and plugins
        run: npm install prettier prettier-plugin-tailwindcss

      - name: Run Pre-Commit
        run: pre-commit run --all-files
